CREATE ALGORITHM=UNDEFINED DEFINER=`kasadevo`@`%` SQL SECURITY DEFINER VIEW `admin_ads_view` AS select `o`.`po_number` AS `po_number`,`o`.`id` AS `order_ads_id`,`o`.`dfp_order_id` AS `dfp_order_id`,`o`.`advertiser_id` AS `advertiser_id`,concat(`o`.`po_number`,'/',`o`.`id`,'/',`o`.`dfp_order_id`,'/',`o`.`advertiser_id`) AS `id_search`,`o`.`created_from` AS `created_from`,`o`.`reason` AS `order_reason`,`l`.`status` AS `line_item_status`,`l`.`cost_type` AS `line_item_cost_type`,`l`.`total_impression_delivered` AS `line_item_total_impression_delivered`,`l`.`total_click_delivered` AS `line_item_total_click_delivered`,`l`.`quantity` AS `line_item_quantity`,`l`.`id` AS `line_item_id`,`l`.`budget` AS `line_item_budget`,`c`.`image_path` AS `creative_image_path`,`c`.`title` AS `creative_title`,`c`.`url` AS `creative_url`,`c`.`name` AS `creative_name`,`c`.`description` AS `creative_description`,`d`.`type` AS `dfp_placement_type`,`dp`.`device` AS `device`,`c`.`type` AS `creative_type` from ((((((`order_ads` `o` join `line_item` `l`) join `creative` `c`) join `lica` `lc`) join `placement` `p`) join `device_placement` `dp`) join `dfp_placement` `d`) where ((`o`.`id` = `l`.`order_ads_id`) and (`lc`.`line_item_id` = `l`.`id`) and (`lc`.`creative_id` = `c`.`id`) and (`p`.`placement_id` = `dp`.`dfp_placement_id`) and (`d`.`id` = `dp`.`placement_id`) and (`p`.`line_item_id` = `l`.`id`) and (`l`.`status` not in (4)) and (`o`.`created_from` = 1)) group by `l`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`kasadevo`@`%` SQL SECURITY DEFINER  VIEW `advertisers_view` AS select `o`.`po_number` AS `po_number`,`o`.`advertiser_id` AS `advertiser_id` from `order_ads` `o` where (`o`.`po_number` is not null) group by `o`.`po_number`;

CREATE ALGORITHM=UNDEFINED DEFINER=`kasadevo`@`%` SQL SECURITY DEFINER  VIEW `impression_bought_view` AS select `o`.`po_number` AS `po_number`,sum(`l`.`quantity`) AS `impression_bought` from (`order_ads` `o` join `line_item` `l`) where ((`o`.`id` = `l`.`order_ads_id`) and (`o`.`po_number` is not null) and (`l`.`cost_type` = 'CPM')) group by `o`.`po_number`;

CREATE ALGORITHM=UNDEFINED DEFINER=`kasadevo`@`%` SQL SECURITY DEFINER  VIEW `click_bought_view` AS select `o`.`po_number` AS `po_number`,sum(`l`.`quantity`) AS `click_bought` from (`order_ads` `o` join `line_item` `l`) where ((`o`.`id` = `l`.`order_ads_id`) and (`o`.`po_number` is not null) and (`l`.`cost_type` = 'CPC')) group by `o`.`po_number`;

CREATE ALGORITHM=UNDEFINED DEFINER=`kasadevo`@`%` SQL SECURITY DEFINER  VIEW `admin_report_transactions_view` AS select `t`.`id` AS `id`,date_format(`t`.`created_date`,'%Y-%m-%d') AS `created_date`,`t`.`total` AS `revenue`,`av`.`advertiser_id` AS `advertiser_id`,ifnull(`ibv`.`impression_bought`,0) AS `impression_bought`,ifnull(`cbv`.`click_bought`,0) AS `click_bought`,`t`.`status` AS `transaction_status`,`t`.`payment_method` AS `payment_method` from (((`transactions` `t` join `advertisers_view` `av` on((convert(concat(`t`.`ref_no`,'/',`t`.`id`) using utf8) = `av`.`po_number`))) left join `impression_bought_view` `ibv` on((convert(concat(`t`.`ref_no`,'/',`t`.`id`) using utf8) = `ibv`.`po_number`))) left join `click_bought_view` `cbv` on((convert(concat(`t`.`ref_no`,'/',`t`.`id`) using utf8) = `cbv`.`po_number`))) order by `t`.`id` desc;

CREATE ALGORITHM=UNDEFINED DEFINER=`kasadevo`@`%` SQL SECURITY DEFINER  VIEW `admin_transaction_detail_view` AS select `o`.`po_number` AS `po_number`,`o`.`dfp_order_id` AS `dfp_order_id`,`o`.`id` AS `id`,`o`.`advertiser_id` AS `advertiser_id`,`c`.`title` AS `title`,`c`.`url` AS `url`,`c`.`description` AS `description`,`c`.`name` AS `name`,`o`.`status` AS `status`,`o`.`reason` AS `reason` from (((`order_ads` `o` join `line_item` `l`) join `creative` `c`) join `lica` `lc`) where ((`o`.`id` = `l`.`order_ads_id`) and (`lc`.`line_item_id` = `l`.`id`) and (`lc`.`creative_id` = `c`.`id`)) group by `o`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`kasadevo`@`%` SQL SECURITY DEFINER  VIEW `payment` AS select distinct `o`.`id` AS `order_ads_id`,`o`.`advertiser_id` AS `advertiser_id`,`l`.`id` AS `line_item_id`,`o`.`status` AS `status`,`c`.`title` AS `title`,`c`.`description` AS `description`,`c`.`url` AS `url`,`c`.`name` AS `creative_name`,`l`.`quantity` AS `quantity`,`o`.`po_number` AS `po_number`,`o`.`created_from` AS `created_from`,`l`.`cost_type` AS `cost_type`,`l`.`budget` AS `budget`,`l`.`start_date_time` AS `start_date_time` from (((`order_ads` `o` join `line_item` `l`) join `creative` `c`) join `lica` `lc`) where ((`o`.`id` = `l`.`order_ads_id`) and (`lc`.`line_item_id` = `l`.`id`) and (`lc`.`creative_id` = `c`.`id`)) group by `o`.`id`;
